<?php
return ['project-id-version'=>'WooCommerce Advanced Shipment Tracking','report-msgid-bugs-to'=>'','pot-creation-date'=>'2020-11-11 09:34+0000','po-revision-date'=>'2025-03-05 05:33+0000','last-translator'=>'','language-team'=>'Spanish (Spain)','language'=>'es_ES','plural-forms'=>'nplurals=2; plural=n != 1;','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.7.1; wp-6.7.2','messages'=>['3plwinner'=>'3plganador','Add'=>'Agregar','Add API Name alias'=>'Agregar alias de nombre de API','Add Custom Carrier'=>'Agregar transportista personalizado','Add shipment tracking information to your WooCommerce orders and provide customers with an easy way to track their orders. Shipment tracking Info will appear in customers accounts (in the order panel) and in WooCommerce order complete email.'=>'Agregue información de seguimiento de envío a sus pedidos de WooCommerce y brinde a los clientes una manera fácil de rastrear sus pedidos. La información de seguimiento del envío aparecerá en las cuentas de los clientes (en el panel de pedidos) y en el correo electrónico completo de pedidos de WooCommerce.','Add Tracking'=>'Agregar seguimiento','Add Tracking - order	'=>'Agregar seguimiento: pedido','Add Tracking Info'=>'Agregar información de seguimiento','Add Tracking Order action'=>'Agregar acción de orden de seguimiento','Additional text after header'=>'Texto adicional después del encabezado','Advanced Shipment Tracking for WooCommerce'=>'Seguimiento avanzado de envíos para WooCommerce','AliExpress Dropshipping'=>'Envío directo de AliExpress','All Carriers Selected.'=>'Todos los transportistas seleccionados.','API aliases'=>'Alias de API','API Date Format'=>'Formato de fecha de API','Are you sure you want to delete this shipping carrier?'=>'¿Está seguro de que desea eliminar este transportista de envío?','AST Customizer'=>'Personalizador AST','Automated CSV Import through FTP/SFTP'=>'Importación automática de CSV a través de FTP/SFTP','Available Placeholders:'=>'Marcadores de posición disponibles:','Background color'=>'Color de fondo','Border color'=>'Color del borde
','Border radius'=>'Radio del borde','Button color'=>'Color del botón','Button font color'=>'Color de fuente del botón','Button radius'=>'Radio del botón','Button size'=>'Tamaño del botón','Button text'=>'Botón de texto','Byrd Fulfillment'=>'Cumplimiento de Byrd','Cannot create existing order shipment tracking.'=>'No se puede crear el seguimiento de envío de pedidos existente.
','Carriers Added'=>'Transportistas agregados','Carriers Deleted'=>'Transportistas eliminados','carriers selected.'=>'transportistas seleccionados.','Carriers Updated'=>'Transportistas actualizados','CartRover'=>'CarroRover','Change order status to'=>'Cambiar el estado del pedido a','Change status to %s'=>'Cambiar estado a %s','Change status to shipped'=>'Cambiar estado a enviado
','Choose for which Order status to display'=>'Elegir en qué Estados de pedido mostrar','Choose the date format that you use when updating the shipment tracking API endpoint from external sources'=>'Elija el formato de fecha que utiliza al actualizar el punto final de la API de seguimiento de envíos desde fuentes externas','Choose the Shipped Date format'=>'Elija el formato de fecha de envío','Choose which Order Status in your store you would like to display Add the Tracking icon in the Order Actions menu.'=>'Elija qué estado del pedido en su tienda le gustaría mostrar. Agregue el ícono de Seguimiento en el menú Acciones del pedido.','Click Here'=>'Haga clic aquí','Completed'=>'Terminada','Continue'=>'Seguir','CSV Import'=>'Importación CSV','CustomCat'=>'Gato personalizado','Customize'=>'Personalizar','Dark Font'=>'Fuente oscura
','Data saved successfully.'=>'Datos guardados exitosamente.','Date shipped:'=>'Fecha de envío:','Dear Systems'=>'Estimados sistemas','Delete'=>'Borrar','Delivered'=>'Entregado','Delivered <span class="count">(%s)</span>'=>'Entregado <span class="count">(%s)</span>' . "\0" . 'Entregado <span class="count">(%s)</span>','Deselect All'=>'Deseleccionar todo','DHL Shipping Germany for WooCommerce'=>'Envío DHL Alemania para WooCommerce','Dianxiaomi'=>'Dianxiaomi','Display shipment status section'=>'Mostrar la sección de estado del envío','Download 	sample csv'=>'Descargar csv de muestra','EasyPost'=>'Correo fácil','Edit'=>'Editar','Edit Shipping Carrier'=>'Editar transportista','EIZ'=>'ZIE','Email Content'=>'Contenido del correo electrónico','Email content'=>'Contenido de correo electronico','Email Customizer'=>'Personalizador de correo electrónico','Email heading'=>'Encabezado de correo electrónico','Email Subject'=>'Asunto del email','Email type'=>'Tipo de correo electrónico','Enable Carriers'=>'Habilitar transportistas','Enable email'=>'Habilitar correo electrónico','Enable Integration'=>'Habilitar integración','Enable Shipping Carriers'=>'Habilitar transportistas de envío','eShipper'=>'Remitente electrónico','Filter by shipping provider'=>'Filtrar por proveedor de envío','Fulfill Order'=>'Cumplir con la orden','General Settings'=>'Configuración general','GLS Sell & Send Italy'=>'GLS Vender y Enviar Italia','Go Pro'=>'Hazte Pro','Hi there. we thought you\'d like to know that the shipment tracking for your recent order from {site_title} has been updated.'=>'Hola. Pensamos que le gustaría saber que se actualizó el seguimiento de envío de su pedido reciente de {site_title}.','Hi there. we thought you\'d like to know that your recent order from {site_title} has been partially shipped.'=>'Hola. pensamos que le gustaría saber que su pedido reciente de {site_title} ha sido enviado parcialmente.
','hide details'=>'ocultar detalles
','Hide shipping provider image'=>'Ocultar imagen del proveedor de envío','Hide tracking header'=>'Ocultar encabezado de seguimiento','How to import 	tracking number from CSV files?'=>'¿Cómo importar el número de seguimiento de archivos CSV?','if you want to select all carriers.'=>'si desea seleccionar todos los operadores.','Import in Progress'=>'Importación en curso','Integrations'=>'integraciones','Interparcel'=>'Interparcel','Invalid order ID.'=>'ID de pedido no válido
','Inventory source'=>'fuente de inventario','JTL-Connector'=>'Conector JTL','Keep 	unchecked for the tracking info to be added to any existing tracking info added to the orders.'=>'Manténgalo desmarcado para que la información de seguimiento se agregue a cualquier información de seguimiento existente agregada a los pedidos.','Large'=>'Largo','Light Font'=>'Fuente de luz
','Linnworks'=>'Fábrica de lino','Mark as Completed?'=>'¿Marcar como completado?
','Mark as Shipped'=>'Marcar como enviado','Mark as Shipped?'=>'¿Marcar como enviado?
','Mark order as delivered'=>'Marcar pedido como entregado','Mark order as:'=>'Marcar orden como:
','Mockup Order'=>'Orden de maqueta','More Info'=>'Más información','Multiple API names mapping is a pro features'=>'La asignación de varios nombres de API es una característica profesional','NetSuite Connector'=>'Conector NetSuite','Normal'=>'Normal','Opt in to get email notifications for security & feature updates'=>'Suscríbase para recibir notificaciones por correo electrónico sobre actualizaciones de seguridad y funciones','Opt in to share some basic WordPress environment info'=>'Opte por compartir información básica sobre el entorno de WordPress','Order Emails Display'=>'Visualización de correos electrónicos de pedidos','Order Statuses'=>'Estados de pedidos','Order Statuses & Notifications'=>'Estados de pedidos y notificaciones','Order was shipped with %1$s and tracking number is: %2$s'=>'El pedido se envió con %1$s y el número de seguimiento es: %2$s','Ordoro'=>'ordoro','ParcelForce'=>'ParcelForce','Partially Shipped'=>'Parcialmente Enviado
','Partially Shipped <span class="count">(%s)</span>'=>'Enviado parcialmente <span class="count">(%s)</span>
' . "\0" . 'Enviado parcialmente <span class="count">(%s)</span>
','PayPal Tracking'=>'Seguimiento de PayPal','Picqer'=>'Picqer','Pirate Ship'=>'Barco pirata','Please add shipping carriers from <a href="%s">here</a>'=>'Por favor agregue transportistas desde <a href="%s">aquí</a>','Please install and activate %1$sWooCommerce%2$s for Advanced Shipment Tracking for WooCommerce!'=>'Por favor, instala y activa %sWooCommerce%s para usar Advanced Shipment Tracking for WooCommerce!','Please upload a valid CSV file.'=>'Sube un archivo CSV válido.','Print Label and Tracking Code for GLS'=>'Imprimir etiqueta y código de seguimiento para GLS','Printful'=>'impreso','Product Code:'=>'Código de producto:','Provider'=>'Proveedor','Qapla'=>'Qapla','QuickBooks Commerce (formerly TradeGecko)'=>'Comercio de QuickBooks (anteriormente TradeGecko)','ReadyToShip'=>'Listo para enviar','Remove Selected'=>'Eliminar selección','Rename the “Completed” Order status label to “Shipped”'=>'Renombrar el estado de pedido "Completado" a "Enviado"','Replace tracking information?'=>'¿Reemplazar la información de seguimiento?','Reset carriers database, it will reset all your shipping provider database'=>'Restablecer la base de datos de los transportistas, restablecerá toda la base de datos de su proveedor de envío','Royal Mail Click & Drop'=>'Haga clic y suelte de Royal Mail','Save & Close'=>'Guardar cerrar','Saved'=>'Salvado','Search by carrier / country'=>'Buscar por transportista / país','Select All'=>'Seleccionar todo','Send Email'=>'Enviar correo electrónico
','Sendcloud'=>'Enviar nube','Sendle'=>'Sendero','Settings'=>'Ajustes','Settings Saved.'=>'Se guardó la configuración.','Shipment status changed to %s'=>'El estado del envío cambió a% s','Shipment Tracking'=>'Rastreo de envío','Shipment Tracking API'=>'API de seguimiento de envíos','Shipped'=>'Enviado','Shipped <span class="count">(%s)</span>'=>'Enviado <span class="count">(%s)</span>
' . "\0" . 'Enviado <span class="count">(%s)</span>
','Shipped on'=>'Embarcado','Shipped on %s'=>'Enviado en% s','Shipped on:'=>'Embarcado:','Shipped Order'=>'Pedido enviado','Shipping Carrier Already Added'=>'Transportista ya agregado','Shipping Carrier Not Found!'=>'¡Transportista no encontrado!','Shipping Carriers'=>'Transportistas de envío','Shipping carriers database reset successfully.'=>'La base de datos de los transportistas se restableció correctamente.','Shipping Provider:'=>'Proveedor de envío:','Shippo'=>'Shippo','Shippypro'=>'shippypro','ShipStation'=>'Estación de barco','Shiptheory'=>'Teoría del barco','Shiptime'=>'Tiempo de envío','Shirtee Cloud'=>'Nube de camisa','SimpleSell'=>'Venta simple','Stamps.com'=>'Sellos.com','Sync Carriers'=>'Operadores de sincronización','Sync Shipping Carriers'=>'Sincronizar transportistas de envío','Syncing the shipping carriers list add or updates the pre-set shipping carriers and will not effect custom shipping carriers.'=>'La sincronización de la lista de transportistas agrega o actualiza los transportistas preestablecidos y no afectará a los transportistas personalizados.','There are some issue with sync, Please Retry.'=>'Hay algún problema con la sincronización. Vuelva a intentarlo.
','This browser does not support HTML5.'=>'Este navegador no es compatible con HTML5.','This option allows you to choose on which order status email you would like to display the tracking information'=>'Esta opción le permite elegir en qué correo electrónico de estado del pedido desea mostrar la información de seguimiento.','Track'=>'Rastrear','Track Shipment'=>'Rastrear envio
','Track Your Order'=>'Rastrea tu orden','Tracker type'=>'Tipo de rastreador','Tracking Button'=>'Botón de seguimiento','Tracking header text'=>'Seguimiento del texto del encabezado
','Tracking info was deleted for tracking provider %1$s with tracking number %2$s'=>'Se eliminó la información de seguimiento del proveedor de seguimiento %1$s con número de seguimiento %2$s','Tracking Number'=>'El número de rastreo','Tracking number:'=>'El número de rastreo:','Tracking Widget'=>'Widget de seguimiento','Undo'=>'Deshacer','Updated Tracking'=>'Seguimiento actualizado
','Updated Tracking <span class="count">(%s)</span>'=>'Seguimiento actualizado <span class="count">(%s)</span>
' . "\0" . 'Seguimiento actualizado <span class="count">(%s)</span>
','Upload a CSV file from your computer:'=>'Sube un archivo CSV desde tu computadora:','Upload again'=>'Subir de nuevo','view details'=>'ver detalles
','View Orders'=>'Ver pedidos','WC Shipping'=>'Envío de WC','We detected %s orders that use the Delivered order status, You can reassign these orders to a different status'=>'Detectamos %s pedidos que usan el estado de pedido Entregado. Puede reasignar estos pedidos a un estado diferente','We detected %s orders that use the Partially Shipped order status, You can reassign these orders to a different status'=>'Detectamos% s pedidos que usan el estado de pedido Enviado parcialmente. Puede reasignar estos pedidos a un estado diferente.','Widget Header'=>'Encabezado de widget','Widget Style'=>'Estilo de widget','WooCommerce Canada Post Shipping'=>'Envío postal de WooCommerce Canadá','WooCommerce Germanized plugin by Vendidero'=>'Plugin germanizado para WooCommerce de Vendidero','WooCommerce GLS plugin by Tehster'=>'Complemento GLS para WooCommerce de Tehster','WooCommerce UPS Shipping'=>'Envío de UPS de WooCommerce','Y-m-d'=>'Y-m-d','You are customizing'=>'tu estas personalizando','You can upload only csv file.'=>'Solo puede cargar un archivo csv.','Your Order is Partially Shipped'=>'Su pedido se envía parcialmente','Your {site_title} order is now partially shipped'=>'Su pedido de {site_title} ahora se envió parcialmente
','Zenventory'=>'Zenventorio']];
