<?php
return ['project-id-version'=>'WooCommerce Advanced Shipment Tracking','report-msgid-bugs-to'=>'','pot-creation-date'=>'2020-11-11 09:34+0000','po-revision-date'=>'2025-03-05 05:33+0000','last-translator'=>'','language-team'=>'Russian','language'=>'ru_RU','plural-forms'=>'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2);','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.7.1; wp-6.7.2','messages'=>['3plwinner'=>'3plпобедитель','Add'=>'Добавлять','Add API Name alias'=>'Добавить псевдоним имени API','Add Custom Carrier'=>'Добавить специального оператора связи','Add shipment tracking information to your WooCommerce orders and provide customers with an easy way to track their orders. Shipment tracking Info will appear in customers accounts (in the order panel) and in WooCommerce order complete email.'=>'Добавьте информацию об отслеживании доставки в свои заказы WooCommerce и предоставьте клиентам простой способ отслеживать свои заказы. Информация об отслеживании доставки будет отображаться в учетных записях клиентов (на панели заказов) и в электронном письме с полным заказом WooCommerce.','Add Tracking'=>'Добавить отслеживание','Add Tracking - order	'=>'Добавить отслеживание - заказ','Add Tracking Info'=>'Добавить информацию отслеживания','Add Tracking Order action'=>'Добавить действие для заказа отслеживания','Additional text after header'=>'Дополнительный текст после заголовка','Advanced Shipment Tracking for WooCommerce'=>'Расширенное отслеживание отгрузки для WooCommerce','AliExpress Dropshipping'=>'Дропшиппинг с AliExpress','All Carriers Selected.'=>'Выбраны все операторы связи.','API aliases'=>'Псевдонимы API','API Date Format'=>'Формат даты API','Are you sure you want to delete this shipping carrier?'=>'Вы уверены, что хотите удалить этого перевозчика?','AST Customizer'=>'Настройщик АСТ','Automated CSV Import through FTP/SFTP'=>'Автоматический импорт CSV через FTP/SFTP','Available Placeholders:'=>'Доступные заполнители:','Background color'=>'Фоновый цвет','Border color'=>'Цвет границы','Border radius'=>'Радиус границы','Button color'=>'Цвет кнопки','Button font color'=>'Цвет шрифта кнопки','Button radius'=>'Радиус кнопки','Button size'=>'Размер кнопки','Button text'=>'Текст кнопки','Byrd Fulfillment'=>'Выполнение Берда','Cannot create existing order shipment tracking.'=>'Невозможно создать существующее отслеживание доставки заказа.
','Carriers Added'=>'Добавлены операторы связи','Carriers Deleted'=>'Операторы связи удалены','carriers selected.'=>'выбраны перевозчики.','Carriers Updated'=>'Перевозчики обновлены','CartRover'=>'КартРовер','Change order status to'=>'Изменить статус заказа на','Change status to %s'=>'Изменить статус на %s','Change status to shipped'=>'Изменить статус на отправленный
','Choose for which Order status to display'=>'Выберите, для какого статуса заказа отображать','Choose the date format that you use when updating the shipment tracking API endpoint from external sources'=>'Выберите формат даты, который вы используете при обновлении конечной точки API отслеживания доставки из внешних источников.','Choose the Shipped Date format'=>'Выберите формат даты отправки','Choose which Order Status in your store you would like to display Add the Tracking icon in the Order Actions menu.'=>'Выберите, какой статус заказа в вашем магазине вы хотите отображать. Добавьте значок отслеживания в меню «Действия по заказу».','Click Here'=>'Кликните сюда','Completed'=>'Завершенный
','Continue'=>'Продолжать','CSV Import'=>'CSV Импорт','CustomCat'=>'CustomCat','Customize'=>'Настроить','Dark Font'=>'Темный шрифт
','Data saved successfully.'=>'Данные успешно сохранены.','Date shipped:'=>'Дата отправки:','Dear Systems'=>'Дорогие системы','Delete'=>'Удалить','Delivered'=>'доставлен','Delivered <span class="count">(%s)</span>'=>'Доставлено <span class="count">(%s)</span>' . "\0" . 'Доставлено <span class="count">(%s)</span>' . "\0" . '','Deselect All'=>'Убрать выделение со всего','DHL Shipping Germany for WooCommerce'=>'Доставка DHL в Германию для WooCommerce','Dianxiaomi'=>'Дяньсяоми','Display shipment status section'=>'Показать раздел статуса отправки','Download 	sample csv'=>'Скачать образец CSV','EasyPost'=>'EasyPost','Edit'=>'Редактировать','Edit Shipping Carrier'=>'Редактировать перевозчика','EIZ'=>'ЭИЗ','Email Content'=>'Содержимое электронной почты','Email content'=>'Содержание электронной почты','Email Customizer'=>'Настройщик электронной почты','Email heading'=>'Заголовок электронной почты','Email Subject'=>'Тема письма','Email type'=>'Тип электронной почты','Enable Carriers'=>'Включить операторов связи','Enable email'=>'Включить электронную почту','Enable Integration'=>'Включить интеграцию','Enable Shipping Carriers'=>'Включить перевозчиков','eShipper'=>'eShipper','Filter by shipping provider'=>'Фильтр по поставщику услуг доставки','Fulfill Order'=>'Выполнить заказ','General Settings'=>'общие настройки','GLS Sell & Send Italy'=>'GLS Продать и отправить в Италию','Go Pro'=>'Go Pro','Hi there. we thought you\'d like to know that the shipment tracking for your recent order from {site_title} has been updated.'=>'Всем привет. мы подумали, что вы хотели бы знать, что отслеживание доставки вашего недавнего заказа с {site_title} было обновлено.','Hi there. we thought you\'d like to know that your recent order from {site_title} has been partially shipped.'=>'Всем привет. мы подумали, что вы хотели бы знать, что ваш недавний заказ с {site_title} частично отправлен.
','hide details'=>'скрыть детали
','Hide shipping provider image'=>'Отобразить изображение поставщика доставки
','Hide tracking header'=>'Скрыть заголовок отслеживания','How to import 	tracking number from CSV files?'=>'Как импортировать номер отслеживания из файлов CSV?','if you want to select all carriers.'=>'если вы хотите выбрать всех операторов связи.','Import in Progress'=>'Выполняется импорт','Integrations'=>'Интеграции','Interparcel'=>'Интерпосылка','Invalid order ID.'=>'Неверный идентификатор заказа.
','Inventory source'=>'Источник инвентаря','JTL-Connector'=>'JTL-разъем','Keep 	unchecked for the tracking info to be added to any existing tracking info added to the orders.'=>'Не устанавливайте флажок, чтобы информация об отслеживании добавлялась к любой существующей информации об отслеживании, добавленной к заказам.','Large'=>'Большой','Light Font'=>'Свет шрифт
','Linnworks'=>'Линнворкс','Mark as Completed?'=>'Отметить как выполненное?
','Mark as Shipped'=>'Отметить как отправленное','Mark as Shipped?'=>'Пометить как отправлен?
','Mark order as delivered'=>'Отметить заказ как доставленный','Mark order as:'=>'Отметить заказ как:
','Mockup Order'=>'Заказ макета','More Info'=>'Больше информации','Multiple API names mapping is a pro features'=>'Сопоставление нескольких имен API - это профессиональные функции','NetSuite Connector'=>'Коннектор NetSuite','Normal'=>'Обычный','Opt in to get email notifications for security & feature updates'=>'Включите получение уведомлений по электронной почте об обновлениях безопасности и функциях.','Opt in to share some basic WordPress environment info'=>'Согласитесь поделиться базовой информацией о среде WordPress.','Order Emails Display'=>'Заказать отображение писем','Order Statuses'=>'Статусы заказов','Order Statuses & Notifications'=>'Статусы заказов и уведомления','Order was shipped with %1$s and tracking number is: %2$s'=>'Заказ был отправлен с помощью %1$s, номер отслеживания: %2$s.','Ordoro'=>'Ордоро','ParcelForce'=>'ParcelForce','Partially Shipped'=>'Частично отправлен
','Partially Shipped <span class="count">(%s)</span>'=>'Частично отправлен <span class="count">(%s)</span>
' . "\0" . 'Частично отправлен <span class="count">(%s)</span>
' . "\0" . 'Частично отправлен <span class="count">(%s)</span>
','PayPal Tracking'=>'Отслеживание PayPal','Picqer'=>'Пикер','Pirate Ship'=>'Пиратский корабль','Please add shipping carriers from <a href="%s">here</a>'=>'Пожалуйста, добавьте перевозчиков <a href="%s">отсюда</a>','Please install and activate %1$sWooCommerce%2$s for Advanced Shipment Tracking for WooCommerce!'=>'Пожалуйста, установите и активируйте %1$sWooCommerce%2$s для расширенного отслеживания поставок для WooCommerce!','Please upload a valid CSV file.'=>'Загрузите действующий файл CSV.','Print Label and Tracking Code for GLS'=>'Распечатайте этикетку и код отслеживания для GLS','Printful'=>'Печатный','Product Code:'=>'Код продукта:','Provider'=>'поставщик','Qapla'=>'Капла','QuickBooks Commerce (formerly TradeGecko)'=>'QuickBooks Commerce (ранее TradeGecko)','ReadyToShip'=>'Готов к отправке','Remove Selected'=>'Убрать выбранное','Rename the “Completed” Order status label to “Shipped”'=>'Переименуйте метку статуса заказа "Завершено" на "Отправлено".','Replace tracking information?'=>'Заменить отслеживающую информацию?','Reset carriers database, it will reset all your shipping provider database'=>'Сбросьте базу данных перевозчиков, это сбросит всю базу данных ваших поставщиков услуг доставки.','Royal Mail Click & Drop'=>'Королевская почта Click & Drop','Save & Close'=>'Сохранить и закрыть','Saved'=>'Сохранено','Search by carrier / country'=>'Поиск по оператору/стране','Select All'=>'Выбрать все','Send Email'=>'Отправить письмо
','Sendcloud'=>'Отправитьоблако','Sendle'=>'Сендл','Settings'=>'Настройки','Settings Saved.'=>'Настройки сохранены.','Shipment status changed to %s'=>'Статус отгрузки изменен на% s','Shipment Tracking'=>'отслеживание посылки','Shipment Tracking API'=>'API отслеживания отправлений','Shipped'=>'Высылаем','Shipped <span class="count">(%s)</span>'=>'Отправлено <span class="count">(%s)</span>
' . "\0" . 'Отправлено <span class="count">(%s)</span>
' . "\0" . 'Отправлено <span class="count">(%s)</span>
','Shipped on'=>'Поставляется на','Shipped on %s'=>'Отправлено на% s','Shipped on:'=>'Поставляется на:','Shipped Order'=>'Отправленный заказ','Shipping Carrier Already Added'=>'Транспортная компания уже добавлена','Shipping Carrier Not Found!'=>'Транспортная компания не найдена!','Shipping Carriers'=>'Транспортные перевозчики','Shipping carriers database reset successfully.'=>'База данных перевозчиков успешно сброшена.','Shipping Provider:'=>'Поставщик доставки:','Shippo'=>'Шиппо','Shippypro'=>'Шиппипро','ShipStation'=>'КорабльСтанция','Shiptheory'=>'Теория корабля','Shiptime'=>'Время доставки','Shirtee Cloud'=>'Облако Ширти','SimpleSell'=>'SimpleSell','Stamps.com'=>'Штампы.com','Sync Carriers'=>'Синхронизация операторов связи','Sync Shipping Carriers'=>'Синхронизировать перевозчиков','Syncing the shipping carriers list add or updates the pre-set shipping carriers and will not effect custom shipping carriers.'=>'Синхронизация списка перевозчиков добавляет или обновляет предустановленные перевозчики и не влияет на пользовательских перевозчиков.','There are some issue with sync, Please Retry.'=>'Возникла проблема с синхронизацией. Повторите попытку.
','This browser does not support HTML5.'=>'Этот браузер не поддерживает HTML5.','This option allows you to choose on which order status email you would like to display the tracking information'=>'Эта опция позволяет вам выбрать, на каком электронном письме о статусе заказа вы хотите отображать информацию об отслеживании.','Track'=>'трек','Track Shipment'=>'Трек Отгрузка
','Track Your Order'=>'Отследить ваш заказ','Tracker type'=>'Тип трекера','Tracking Button'=>'Кнопка отслеживания','Tracking header text'=>'Текст заголовка отслеживания
','Tracking info was deleted for tracking provider %1$s with tracking number %2$s'=>'Информация отслеживания удалена для поставщика отслеживания %1$s с номером отслеживания %2$s.','Tracking Number'=>'Номер Отслеживания','Tracking number:'=>'Идентификационный номер:','Tracking Widget'=>'Виджет отслеживания','Undo'=>'Отменить','Updated Tracking'=>'Обновленное отслеживание
','Updated Tracking <span class="count">(%s)</span>'=>'Обновленное отслеживание <span class="count">(%s)</span>
' . "\0" . 'Обновленное отслеживание <span class="count">(%s)</span>
' . "\0" . 'Обновленное отслеживание <span class="count">(%s)</span>
','Upload a CSV file from your computer:'=>'Загрузите файл CSV со своего компьютера:','Upload again'=>'Загрузить снова','view details'=>'посмотреть детали
','View Orders'=>'Посмотреть заказы','WC Shipping'=>'Туалет Доставка','We detected %s orders that use the Delivered order status, You can reassign these orders to a different status'=>'Мы обнаружили %s заказов со статусом «Доставлен». Вы можете переназначить этим заказам другой статус.','We detected %s orders that use the Partially Shipped order status, You can reassign these orders to a different status'=>'Мы обнаружили заказы% s со статусом "Частично отправлено". Вы можете переназначить эти заказы на другой статус.','Widget Header'=>'Заголовок виджета','Widget Style'=>'Стиль виджета','WooCommerce Canada Post Shipping'=>'WooCommerce Почтовая доставка Канады','WooCommerce Germanized plugin by Vendidero'=>'Плагин WooCommerce Germanized от Vendidero','WooCommerce GLS plugin by Tehster'=>'Плагин WooCommerce GLS от Tehster','WooCommerce UPS Shipping'=>'Доставка WooCommerce UPS','Y-m-d'=>'Г-м-д','You are customizing'=>'Вы настраиваете','You can upload only csv file.'=>'Вы можете загружать только файл csv.','Your Order is Partially Shipped'=>'Ваш заказ частично отправлен','Your {site_title} order is now partially shipped'=>'Ваш {site_title} заказ частично отправлен
','Zenventory'=>'Зенвентори']];
