<?php
return ['project-id-version'=>'WooCommerce Advanced Shipment Tracking','report-msgid-bugs-to'=>'','pot-creation-date'=>'2020-11-11 09:34+0000','po-revision-date'=>'2025-03-05 05:33+0000','last-translator'=>'','language-team'=>'Portuguese (Portugal)','language'=>'pt_PT','plural-forms'=>'nplurals=2; plural=n != 1;','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.7.1; wp-6.7.2','messages'=>['3plwinner'=>'3plwinner','Add'=>'Adicionar','Add API Name alias'=>'Adicionar nome de API alias','Add Custom Carrier'=>'Adicionar operadora personalizada','Add shipment tracking information to your WooCommerce orders and provide customers with an easy way to track their orders. Shipment tracking Info will appear in customers accounts (in the order panel) and in WooCommerce order complete email.'=>'Adicione informações de rastreamento de remessa aos seus pedidos do WooCommerce e forneça aos clientes uma maneira fácil de rastrear seus pedidos. As informações de rastreamento de remessa aparecerão nas contas dos clientes (no painel de pedidos) e no e-mail completo do pedido do WooCommerce.','Add Tracking'=>'Adicionar rastreamento','Add Tracking - order	'=>'Adicionar rastreamento - pedido','Add Tracking Info'=>'Adicionar informações de rastreamento','Add Tracking Order action'=>'Adicionar ação de pedido de rastreamento','Additional text after header'=>'Texto adicional após o cabeçalho
','Advanced Shipment Tracking for WooCommerce'=>'Rastreamento avançado de remessa para WooCommerce','AliExpress Dropshipping'=>'AliExpress','All Carriers Selected.'=>'Todas as operadoras selecionadas.','API aliases'=>'Aliases de API','API Date Format'=>'Formato de data API','Are you sure you want to delete this shipping carrier?'=>'Tem certeza de que deseja excluir esta transportadora?','AST Customizer'=>'Personalizador AST','Automated CSV Import through FTP/SFTP'=>'Importação automatizada de CSV via FTP/SFTP','Available Placeholders:'=>'Espaços reservados disponíveis:','Background color'=>'Cor de fundo','Border color'=>'Cor da borda
','Border radius'=>'Raio da borda','Button color'=>'Cor do botao','Button font color'=>'Cor da fonte do botão','Button radius'=>'Raio do botão','Button size'=>'Tamanho do botão','Button text'=>'Botão de texto','Byrd Fulfillment'=>'Cumprimento de Byrd','Cannot create existing order shipment tracking.'=>'Não é possível criar o rastreamento de remessa de pedidos existente.
','Carriers Added'=>'Operadoras adicionadas','Carriers Deleted'=>'Operadoras excluídas','carriers selected.'=>'operadoras selecionadas.','Carriers Updated'=>'Operadoras atualizadas','CartRover'=>'CartRover','Change order status to'=>'Alterar o status do pedido para','Change status to %s'=>'Alterar status para %s','Change status to shipped'=>'Alterar status para enviado
','Choose for which Order status to display'=>'Escolha para qual status do pedido exibir','Choose the date format that you use when updating the shipment tracking API endpoint from external sources'=>'Escolha o formato de data que você usa ao atualizar o endpoint da API de rastreamento de remessas de fontes externas','Choose the Shipped Date format'=>'Escolha o formato da data de envio','Choose which Order Status in your store you would like to display Add the Tracking icon in the Order Actions menu.'=>'Escolha qual status do pedido em sua loja você gostaria de exibir. Adicione o ícone Rastreamento no menu Ações do pedido.','Click Here'=>'Clique aqui','Completed'=>'Concluída','Continue'=>'Continuar','CSV Import'=>'Importação de CSV','CustomCat'=>'Gato Personalizado','Customize'=>'Customizar','Dark Font'=>'Fonte escura
','Data saved successfully.'=>'Dados salvos com sucesso.','Date shipped:'=>'Data de envio:
','Dear Systems'=>'Caros Sistemas','Delete'=>'Excluir','Delivered'=>'Entregue
','Delivered <span class="count">(%s)</span>'=>'Entregue <span class="count">(%s)</span>' . "\0" . 'Entregue <span class="count">(%s)</span>','Deselect All'=>'Desmarcar todos','DHL Shipping Germany for WooCommerce'=>'DHL enviando Alemanha para WooCommerce','Dianxiaomi'=>'Dianxiaomi','Display shipment status section'=>'Exibir seção de status de envio','Download 	sample csv'=>'Baixar exemplo csv','EasyPost'=>'Postagem fácil','Edit'=>'Editar','Edit Shipping Carrier'=>'Editar transportadora','EIZ'=>'EIZ','Email Content'=>'Conteúdo do e-mail','Email content'=>'Conteúdo de email
','Email Customizer'=>'Personalizador de e-mail','Email heading'=>'Cabeçalho do e-mail','Email Subject'=>'Assunto do email','Email type'=>'Tipo de Email','Enable Carriers'=>'Habilitar operadoras','Enable email'=>'Ativar e-mail','Enable Integration'=>'Habilitar integração','Enable Shipping Carriers'=>'Habilitar transportadoras','eShipper'=>'eShipper','Filter by shipping provider'=>'Filtrar por transportadora','Fulfill Order'=>'Cumprir o pedido','General Settings'=>'Configurações Gerais
','GLS Sell & Send Italy'=>'GLS Vender e Enviar Itália','Go Pro'=>'Torne-se Pro','Hi there. we thought you\'d like to know that the shipment tracking for your recent order from {site_title} has been updated.'=>'Olá. achamos que você gostaria de saber que o rastreamento de remessa para seu pedido recente de {site_title} foi atualizado.','Hi there. we thought you\'d like to know that your recent order from {site_title} has been partially shipped.'=>'Olá. achamos que você gostaria de saber que seu pedido recente de {site_title} foi parcialmente enviado.
','hide details'=>'detalhes ocultos
','Hide shipping provider image'=>'Exibir imagem do fornecedor de remessa
','Hide tracking header'=>'Ocultar cabeçalho de rastreamento','How to import 	tracking number from CSV files?'=>'Como importar o número de rastreamento de arquivos CSV?','if you want to select all carriers.'=>'se você quiser selecionar todas as operadoras.','Import in Progress'=>'Importação em andamento','Integrations'=>'Integrações','Interparcel'=>'Interparcel','Invalid order ID.'=>'ID de pedido inválido.
','Inventory source'=>'Fonte de inventário','JTL-Connector'=>'Conector JTL','Keep 	unchecked for the tracking info to be added to any existing tracking info added to the orders.'=>'Mantenha desmarcado para que as informações de rastreamento sejam adicionadas a qualquer informação de rastreamento existente adicionada aos pedidos.','Large'=>'Grande','Light Font'=>'Fonte Light
','Linnworks'=>'Trabalhos de Linn','Mark as Completed?'=>'Marcar como concluído?','Mark as Shipped'=>'Marcar como enviado','Mark as Shipped?'=>'Marcar como enviado?
','Mark order as delivered'=>'Marcar pedido como entregue','Mark order as:'=>'Marque o pedido como:
','Mockup Order'=>'Ordem de maquete','More Info'=>'Mais informações','Multiple API names mapping is a pro features'=>'O mapeamento de vários nomes de API é um recurso profissional','NetSuite Connector'=>'Conector NetSuite','Normal'=>'Normal','Opt in to get email notifications for security & feature updates'=>'Ative para receber notificações por e-mail sobre atualizações de segurança e recursos','Opt in to share some basic WordPress environment info'=>'Opte por compartilhar algumas informações básicas do ambiente WordPress','Order Emails Display'=>'Exibição de e-mails de pedidos','Order Statuses'=>'Status do pedido','Order Statuses & Notifications'=>'Status e notificações de pedidos','Order was shipped with %1$s and tracking number is: %2$s'=>'O pedido foi enviado com %1$s e o número de rastreamento é: %2$s','Ordoro'=>'Ordoro','ParcelForce'=>'ParcelForce','Partially Shipped'=>'enviado parcialmente
','Partially Shipped <span class="count">(%s)</span>'=>'Parcialmente enviado <span class="count">(%s)</span>' . "\0" . 'Parcialmente enviado <span class="count">(%s)</span>','PayPal Tracking'=>'Rastreamento do PayPal','Picqer'=>'Picador','Pirate Ship'=>'Navio pirata','Please add shipping carriers from <a href="%s">here</a>'=>'Adicione transportadoras <a href="%s">aqui</a>','Please install and activate %1$sWooCommerce%2$s for Advanced Shipment Tracking for WooCommerce!'=>'Instale e ative %1$sWooCommerce%2$s para rastreamento avançado de remessas para WooCommerce!','Please upload a valid CSV file.'=>'Faça upload de um arquivo CSV válido.','Print Label and Tracking Code for GLS'=>'Imprimir etiqueta e código de rastreamento para GLS','Printful'=>'Impresso','Product Code:'=>'Código do produto:','Provider'=>'Fornecedor','Qapla'=>'Qapla','QuickBooks Commerce (formerly TradeGecko)'=>'QuickBooks Commerce (anteriormente TradeGecko)','ReadyToShip'=>'Pronto para enviar','Remove Selected'=>'Remover selecionado','Rename the “Completed” Order status label to “Shipped”'=>'Renomeie a etiqueta de status do pedido “Concluído” para “Enviado”','Replace tracking information?'=>'Substituir informações de rastreamento?','Reset carriers database, it will reset all your shipping provider database'=>'Redefinir o banco de dados das transportadoras, isso irá redefinir todo o banco de dados do seu fornecedor de remessa','Royal Mail Click & Drop'=>'Clique e solte do Royal Mail','Save & Close'=>'Salvar fechar','Saved'=>'Salvou','Search by carrier / country'=>'Pesquise por operadora/país','Select All'=>'Selecionar tudo','Send Email'=>'Enviar email
','Sendcloud'=>'Sendcloud','Sendle'=>'Enviar','Settings'=>'Definições','Settings Saved.'=>'Configurações salvas.
','Shipment status changed to %s'=>'Shipment status changed to %s','Shipment Tracking'=>'Rastreamento de Remessa
','Shipment Tracking API'=>'API de rastreamento de remessa','Shipped'=>'Enviada','Shipped <span class="count">(%s)</span>'=>'Enviado <span class="count">(%s)</span>' . "\0" . 'Enviado <span class="count">(%s)</span>','Shipped on'=>'Embarcado','Shipped on %s'=>'Enviado em %s
','Shipped on:'=>'Embarcado:','Shipped Order'=>'Pedido Enviado','Shipping Carrier Already Added'=>'Transportadora já adicionada','Shipping Carrier Not Found!'=>'Transportadora não encontrada!','Shipping Carriers'=>'Transportadoras','Shipping carriers database reset successfully.'=>'Banco de dados de transportadoras redefinido com sucesso.','Shipping Provider:'=>'Fornecedor de envio:','Shippo'=>'navio','Shippypro'=>'Shippypro','ShipStation'=>'Estação de Navio','Shiptheory'=>'Teoria do navio','Shiptime'=>'Tempo de envio','Shirtee Cloud'=>'Camisa Nuvem','SimpleSell'=>'Venda Simples','Stamps.com'=>'Selos.com','Sync Carriers'=>'Sincronizar operadoras','Sync Shipping Carriers'=>'Sincronizar transportadoras','Syncing the shipping carriers list add or updates the pre-set shipping carriers and will not effect custom shipping carriers.'=>'A sincronização da lista de transportadoras adiciona ou atualiza as transportadoras predefinidas e não afetará as transportadoras personalizadas.','There are some issue with sync, Please Retry.'=>'Há algum problema com a sincronização. Tente novamente.
','This browser does not support HTML5.'=>'Este navegador não oferece suporte a HTML5.','This option allows you to choose on which order status email you would like to display the tracking information'=>'Esta opção permite que você escolha em qual e-mail de status do pedido você gostaria de exibir as informações de rastreamento','Track'=>'Track','Track Shipment'=>'Rastrear Remessa
','Track Your Order'=>'Acompanhe seu pedido','Tracker type'=>'Tipo de rastreador','Tracking Button'=>'Botão de rastreamento','Tracking header text'=>'Texto do cabeçalho de rastreamento
','Tracking info was deleted for tracking provider %1$s with tracking number %2$s'=>'As informações de rastreamento foram excluídas do provedor de rastreamento %1$s com número de rastreamento %2$s','Tracking Number'=>'Numero de rastreio
','Tracking number:'=>'Numero de rastreio:
','Tracking Widget'=>'Widget de rastreamento','Undo'=>'Desfazer','Updated Tracking'=>'Rastreamento atualizado
','Updated Tracking <span class="count">(%s)</span>'=>'Rastreamento atualizado <span class="count">(%s)</span>
' . "\0" . 'Rastreamento atualizado <span class="count">(%s)</span>
','Upload a CSV file from your computer:'=>'Faça upload de um arquivo CSV do seu computador:','Upload again'=>'Carregar novamente','view details'=>'ver detalhes
','View Orders'=>'Ver pedidos','WC Shipping'=>'Envio de WC','We detected %s orders that use the Delivered order status, You can reassign these orders to a different status'=>'Detectamos %s pedidos que usam o status do pedido Entregue. Você pode reatribuir esses pedidos a um status diferente','We detected %s orders that use the Partially Shipped order status, You can reassign these orders to a different status'=>'Detectamos% s pedidos que usam o status de pedido parcialmente enviado. Você pode reatribuir esses pedidos a um status diferente','Widget Header'=>'Cabeçalho do widget','Widget Style'=>'Estilo do widget','WooCommerce Canada Post Shipping'=>'Envio postal WooCommerce Canadá','WooCommerce Germanized plugin by Vendidero'=>'Plugin WooCommerce Germanizado por Vendidero','WooCommerce GLS plugin by Tehster'=>'Plugin WooCommerce GLS da Tehster','WooCommerce UPS Shipping'=>'Envio UPS WooCommerce','Y-m-d'=>'A-m-d','You are customizing'=>'Você está personalizando','You can upload only csv file.'=>'Você pode fazer upload apenas de arquivos csv.','Your Order is Partially Shipped'=>'Seu pedido foi parcialmente enviado','Your {site_title} order is now partially shipped'=>'Seu pedido de {site_title} agora foi enviado parcialmente
','Zenventory'=>'Zenventório']];
